### ISSUE TITLE
Fixed working directory

### ISSUE THREAD

**Issue by CookieDecide** [CookieDecide/nadjul#20]
We  should consider to set the workind directory in main.py if we are working with relative paths.
For example like so:

abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

This would set our working directory to the folder that contains main.py.

**Comment by Darkuuu** [comment]
Sounds fine to me, would probably cause less pain when running the python script under different environments.

But when making it static, I would not set it to the src/ folder (where main.py) lies. This is confusing when you are using a module in e.g. src/util and want to access for example img/.

I would suggest to set the wd as the root folder of this repository, so you can access images from any module with "img/" and not "../img". Is this possible?

**Comment by CookieDecide** [comment]
This will work, i just need  to adjust all the relative paths we have used up until now.
I agree that setting it to the root folder is a good idea.
